# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(441, 354)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.loadTableButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadTableButton.sizePolicy().hasHeightForWidth())
        self.loadTableButton.setSizePolicy(sizePolicy)
        self.loadTableButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.loadTableButton.setObjectName("loadTableButton")
        self.horizontalLayout.addWidget(self.loadTableButton)
        self.editTableButton = QtWidgets.QPushButton(self.centralwidget)
        self.editTableButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.editTableButton.setObjectName("editTableButton")
        self.horizontalLayout.addWidget(self.editTableButton)
        self.deleteRowButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteRowButton.setMaximumSize(QtCore.QSize(16777215, 30))
        self.deleteRowButton.setObjectName("deleteRowButton")
        self.horizontalLayout.addWidget(self.deleteRowButton)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.listTables = QtWidgets.QComboBox(self.centralwidget)
        self.listTables.setObjectName("listTables")
        self.gridLayout.addWidget(self.listTables, 0, 0, 1, 1)
        self.dbTable = QtWidgets.QTableWidget(self.centralwidget)
        self.dbTable.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dbTable.sizePolicy().hasHeightForWidth())
        self.dbTable.setSizePolicy(sizePolicy)
        self.dbTable.setObjectName("dbTable")
        self.dbTable.setColumnCount(0)
        self.dbTable.setRowCount(0)
        self.dbTable.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.dbTable, 2, 0, 1, 1)
        self.addRowTable = QtWidgets.QTableWidget(self.centralwidget)
        self.addRowTable.setMaximumSize(QtCore.QSize(16777215, 30))
        self.addRowTable.setRowCount(1)
        self.addRowTable.setObjectName("addRowTable")
        self.addRowTable.setColumnCount(0)
        self.addRowTable.horizontalHeader().setVisible(False)
        self.addRowTable.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.addRowTable, 4, 0, 1, 1)
        self.addRowButton = QtWidgets.QPushButton(self.centralwidget)
        self.addRowButton.setObjectName("addRowButton")
        self.gridLayout.addWidget(self.addRowButton, 5, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 441, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loadTableButton.setText(_translate("MainWindow", "Загрузить данные"))
        self.editTableButton.setText(_translate("MainWindow", "Редактировать таблицу"))
        self.deleteRowButton.setText(_translate("MainWindow", "Удалить строку"))
        self.addRowButton.setText(_translate("MainWindow", "Добавить запись"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
